/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro;

import login.*;
import cadastro.CadastroView;
import java.util.Set;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import login.model.controller.LoginController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author kaiky
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        JbuttonCadastrar = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField1Nome = new javax.swing.JTextField();
        jTextField6Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 204, 255));
        jTextField2.setText("Nome");
        jTextField2.setAutoscrolls(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 204, 255));
        jTextField3.setText("Senha");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jPasswordField1Senha.setText("jPasswordField1");
        jPanel1.add(jPasswordField1Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 20));

        JbuttonCadastrar.setBackground(new java.awt.Color(153, 204, 255));
        JbuttonCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JbuttonCadastrar.setText("Cadastrar");
        JbuttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(JbuttonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(51, 204, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setText("Cadastrar Novo Usuario");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 230, 50));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(51, 204, 255));
        jTextField5.setText("E-mail");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel1.add(jTextField1Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, -1));
        jPanel1.add(jTextField6Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonCadastrarActionPerformed

        
        if(jTextField1Nome.getText().matches("") || jTextField6Email.getText().matches( "") ||  jPasswordField1Senha.getText().matches("")){
        JOptionPane.showMessageDialog(rootPane," Preencha todos os campos ");
  
        
    }else{
           
try{
    LoginController cadastro = new LoginController();
cadastro.cadastroUsuario(this);

 
} catch (SQLException sql) {
    
} 
JOptionPane.showMessageDialog(rootPane, "Cadastro Efetuado");
    this.setVisible(false);
  }
       
                // TODO add your handling code here:
    }//GEN-LAST:event_JbuttonCadastrarActionPerformed

    public JPasswordField getjPasswordField1Senha() {
        return jPasswordField1Senha;
    }

    public void setjPasswordField1Senha(JPasswordField jPasswordField1Senha) {
        this.jPasswordField1Senha = jPasswordField1Senha;
    }

    public JTextField getjTextField1Nome() {
        return jTextField1Nome;
    }

    public void setjTextField1Nome(JTextField jTextField1Nome) {
        this.jTextField1Nome = jTextField1Nome;
    }

    public JTextField getjTextField6Email() {
        return jTextField6Email;
    }

    public void setjTextField6Email(JTextField jTextField6Email) {
        this.jTextField6Email = jTextField6Email;
    }

    
    
    
    
    
    
    
    
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonCadastrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JTextField jTextField1Nome;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6Email;
    // End of variables declaration//GEN-END:variables

    public Object getjTextFieldNome() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getjPasswordFieldSenha() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getjTextFieldEmail() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
